config/routes.rb
Nonna::Application.routes.draw do

  resources :products
  resources :variables

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  get "home/index"
  root :to => "home#index"
end

app/models/option.rb
class Option < ActiveRecord::Base

  belongs_to :variable

  validates_presence_of :name, :code
  validates_uniqueness_of :code
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :variables
  accepts_nested_attributes_for :variables

  validates_presence_of :name, :code
  validates_uniqueness_of :code

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/variable.rb
class Variable < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_many :options

  accepts_nested_attributes_for :options, allow_destroy: true

  validates_presence_of :name, :code
  validates_uniqueness_of :code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :store_location

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    if (request.fullpath != "/users/sign_in" && \
        request.fullpath != "/users/sign_up" && \
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :code, :variable_ids => [])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_variable, only: [:show, :edit, :update, :destroy]

  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
  end

  # GET /variables/new
  def new
    @variable = Variable.new
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render action: 'show', status: :created, location: @variable }
      else
        format.html { render action: 'new' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_variable
    @variable = Variable.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def variable_params
    params.require(:variable).permit(:name, :code, options_attributes: [:id, :name, :code, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors(model)
    render partial: "layouts/errors",
           locals: {model: model}
  end

  def notices
    render partial: "layouts/notice"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="example-orbit" data-orbit>
      <li><%= image_tag "pizza1.png" %></li>
      <li><%= image_tag "pizza2.jpg" %></li>
      <li><%= image_tag "pizza3.jpg" %></li>
    </ul>
  </div>
</div>

<hr/>


<!-- Three-up Content Blocks -->

<div class="row">
  <div class="large-4 columns">
    <%= image_tag "massa1.jpg" %>
    <h4>Massas</h4>

    <p>Conheça as melhores massas da região.

    <p>
  </div>

  <div class="large-4 columns">
    <%= image_tag "salada1.jpg" %>
    <h4>Saladas</h4>

    <p>Se você prefere um prato mais leve chegou a hora de aproveitar as nossas saladas.</p>
  </div>

  <div class="large-4 columns">
    <%= image_tag "sobremesa1.jpg" %>
    <h4>Sobremesas</h4>

    <p>Louco por doces? Confira as nossas deliciosas sobremesas.</p>
  </div>

</div>

<!-- Call to Action Panel -->
<div class="row">
  <div class="large-12 columns">

    <div class="panel">
      <h4>Entre em contato conosco!</h4>

      <div class="row">
        <div class="large-9 columns">
          <p>Conte-nos um pouco sobre a sua experiência comendo com a Pizzaria Nona</p>
        </div>
        <div class="large-3 columns">
          <a href="#" class="radius button right">Contato</a>
        </div>
      </div>
    </div>

  </div>
</div>

<!-- Footer -->

<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Pizzaria Nonna 2014</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Home</a></li>
          <li><a href="#">Pedido Online</a></li>
          <li><a href="#">Lojas</a></li>
          <li><a href="#">Contato</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<script>
    $(document).foundation();
</script>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
    <% model.errors.full_messages.each do |msg| %>
        <div data-alert class="alert-box warning">
          <%= msg %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice %>
    <div data-alert class="alert-box info">
      <%= notice %>
      <a href="#" class="close">&times;</a>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nonna</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="large-3 columns">
    <h1><%= image_tag "logo.png" %></h1>
  </div>
  <div class="large-9 columns menu-pizzaria">
    <ul class="right button-group">
      <li><%= link_to "Home", home_index_path, class: "button" %></li>
      <li><a href="#" class="button">Pedido Online</a></li>
      <li><a href="#" class="button">Lojas</a></li>
      <li><a href="#" class="button">Contato</a></li>
      <% if user_signed_in? %>
          <a href="#" data-dropdown="drop1" class="button dropdown">Administração</a><br>
          <ul id="drop1" data-dropdown-content class="f-dropdown">
            <li><%= link_to "Produtos", products_path %></li>
            <li><%= link_to "Variáveis", variables_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
      <% else %>
          <li><%= link_to "Login", new_user_registration_path, class: "button" %></li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= errors @product %>

<%= form_for(@product) do |f| %>
    <fieldset>
      <legend>Produto</legend>

      <label for="text_code"><%= t("activerecord.attributes.product.code") %>
        <%= f.text_field :code, id: "text_code", placeholder: t("activerecord.attributes.product.code") %>
      </label>

      <label for="text_name"><%= t("activerecord.attributes.product.name") %>
        <%= f.text_field :name, id: "text_name", placeholder: t("activerecord.attributes.product.name") %>
      </label>

      <fieldset>
        <legend>Variáveis associadas</legend>
        <%= f.collection_check_boxes(:variable_ids, Variable.all, :id, :name) %>
      </fieldset>

      <div class="row">
        <div class="large-8 columns">
          <%= f.submit class: "button success radius" %>
          <%= link_to 'Voltar', products_path, class: "button small radius secondary" %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/products/edit.html.erb
<h1><%= @product.name %></h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @product, class: "button radius" %>

app/views/products/index.html.erb
<h1>Produtos</h1>
<%= link_to t("helpers.submit.create", model: t("activerecord.models.product")), new_product_path, class: "button radius" %>

<% if @products.present? %>
    <table>
      <thead>
      <tr>
        <th><%= t("activerecord.attributes.product.code") %></th>
        <th><%= t("activerecord.attributes.product.name") %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.code %></td>
            <td><%= product.name %></td>
            <td><%= link_to 'Mostrar', product %></td>
            <td><%= link_to 'Editar', edit_product_path(product) %></td>
            <td><%= link_to 'Apagar', product, method: :delete, data: {confirm: t("general.messages.confirmation")} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

app/views/products/new.html.erb
<h1><%= t("helpers.submit.create", model: t("activerecord.models.product")) %></h1>

<%= render 'form' %>

app/views/products/show.html.erb
<%= notices %>
<%= errors @product %>


<h1><%= @product.name %></h1>

<p>
  <strong><%= "#{t("activerecord.attributes.product.code")}: " %></strong>
  <%= @product.code %>
</p>


<h3>Variáveis</h3>
<div>
  <ol>
    <% for variable in @product.variables %>
        <p>
          <strong><%= "#{t("activerecord.attributes.variable.name")}:" %></strong>
          <%= variable.name %>
        </p>

        <p>
          <strong><%= "#{t("activerecord.attributes.variable.code")}:" %></strong>
          <%= variable.code %>
        </p>
    <% end %>
  </ol>
</div>

<%= link_to 'Editar', edit_product_path(@product), class: "button radius" %>
<%= link_to 'Voltar', products_path, class: "button small radius secondary" %>

app/views/variables/_form.html.erb
<%= errors @variable %>

<%= nested_form_for @variable do |f| %>


    <fieldset>
      <legend>Variável</legend>

      <label for="text_code"><%= t("activerecord.attributes.variable.code") %>
        <%= f.text_field :code, id: "text_code", placeholder: t("activerecord.attributes.variable.code") %>
      </label>

      <label for="text_name"><%= t("activerecord.attributes.variable.exibition_name") %>
        <%= f.text_field :name, id: "text_name", placeholder: t("activerecord.attributes.variable.exibition_name") %>
      </label>


      <%= f.fields_for :options do |option_form| %>

          <fieldset>
            <legend>Opções</legend>

            <label for="option_code"><%= t("activerecord.attributes.option.code") %>
              <%= option_form.text_field :code, id: "option_code", placeholder: t("activerecord.attributes.option.code") %>
            </label>
            <label for="option_name"><%= t("activerecord.attributes.option.name") %>
              <%= option_form.text_field :name, id: "option_name", placeholder: t("activerecord.attributes.option.name") %>
            </label>

            <%= option_form.link_to_remove t("helpers.submit.remove") %>
          </fieldset>
      <% end %>
      <p><%= f.link_to_add t("helpers.submit.add", model: t("activerecord.models.option")), :options %></p>

      <div class="row">
        <div class="large-8 columns">
          <%= f.submit class: "button success radius" %>
          <%= link_to 'Voltar', variables_path, class: "button small radius secondary" %>
        </div>
      </div>
    </fieldset>



<% end %>

app/views/variables/edit.html.erb
<h1><%= @variable.name %></h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @variable, class: "button radius" %>

app/views/variables/index.html.erb
<h1>Variáveis</h1>
<%= link_to t("helpers.submit.create", model: t("activerecord.models.variable")), new_variable_path, class: "button radius" %>
<% if @variables.present? %>
    <table>
      <thead>
      <tr>
        <th><%= t("activerecord.attributes.variable.code") %></th>
        <th><%= t("activerecord.attributes.variable.exibition_name") %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @variables.each do |variable| %>
          <tr>
            <td><%= variable.code %></td>
            <td><%= variable.name %></td>
            <td><%= link_to 'Mostrar', variable %></td>
            <td><%= link_to 'Editar', edit_variable_path(variable) %></td>
            <td><%= link_to 'Apagar', variable, method: :delete, data: {confirm: t("general.messages.confirmation")} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

app/views/variables/new.html.erb
<h1><%= t("helpers.submit.create", model: t("activerecord.models.variable")) %></h1>

<%= render 'form' %>

app/views/variables/show.html.erb
<%= notices %>
<%= errors @variable %>


<h1><%= @variable.name %></h1>

<p>
  <strong><%= "#{t("activerecord.attributes.variable.code")}: " %></strong>
  <%= @variable.code %>
</p>


<h3>Opcões</h3>
<div>
  <ol>
    <% for option in @variable.options %>
        <p>
          <strong><%= "#{t("activerecord.attributes.option.name")}:" %></strong>
          <%= option.name %>
        </p>

        <p>
          <strong><%= "#{t("activerecord.attributes.option.code")}:" %></strong>
          <%= option.code %>
        </p>
    <% end %>
  </ol>
</div>

<%= link_to 'Editar', edit_variable_path(@variable), class: "button radius" %>
<%= link_to 'Voltar', variables_path, class: "button small radius secondary" %>